version: '3.7'
x-node:
  &default-node
  build: ./node
  env_file: ./secret/node.env
  secrets:
    - authorized_keys
  privileged: true
  tty: true
  tmpfs:
    #- /run:size=100M
    - /run/lock:size=100M
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  networks:
    - jepsen
  ports:
    - ${JEPSEN_PORT:-22}

secrets:
  authorized_keys:
    file: ./secret/authorized_keys

services:
  control:
    container_name: jepsen-control
    hostname: control
    depends_on:
      - redis-cache
      - redis-db
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    ports:
      - "8080"
    networks:
      - jepsen
  redis-cache:
    << : *default-node
    container_name: jepsen-redis-cache
    hostname: redis-cache
  redis-db:
    << : *default-node
    container_name: jepsen-redis-db
    hostname: redis-db

networks:
  jepsen:
